name: Trigger Main Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger_main_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devops
        uses: actions/checkout@v4
        with:
          repository: ConRose456/SE-DevOps
          token: ${{ secrets.MY_GH_PAT }}
          path: devops
      
      - name: Configure npm to use GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GH_PAT }}" > devops/.npmrc
          echo "@conrose456:registry=https://npm.pkg.github.com/" >> ~/.npmrc

      - name: Publish new version
        run: |
          cd devops && npm run publish:github
          
      - name: Trigger SE-DevOpsCDK Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.MY_GH_PAT }}" \
            -d '{"event_type": "se-devops-trigger"}' \
            https://api.github.com/repos/conrose456/SE-DevOpsCDK/dispatches

  